# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9630a836ac3398bc2f29337e64b1d22d3ba823b5bc8b3d371b88c51f84547c49c5af7f0437b743deee9227b4fffae26bc972ce6775ed32fdcc97ac11f0e8e70

test:
  secret_key_base: 748add6b8cdbc707faec0623931c863cb7bb8c6b57b3810bac7aa16aa0c4c28945a47b7f3dc34b43a9dcd26188a65c65fa020bc77f1ac339f101353ed3072a21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
